# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-ideas-home-assignment"
client_id = "016ef78aa6dc46eff76dfc70e3880d92"
application_url = "https://coin-cyprus-larry-from.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://coin-cyprus-larry-from.trycloudflare.com/auth/callback",
  "https://coin-cyprus-larry-from.trycloudflare.com/auth/shopify/callback",
  "https://coin-cyprus-larry-from.trycloudflare.com/api/auth/callback",
  "https://coin-cyprus-larry-from.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-35.myshopify.com"
